[project]
name = "jax-triton"
version = "0.1.3"
description = "JAX + OpenAI Triton integration"
readme = "README.md"
requires-python = ">=3.7,<3.11"
dependencies = [
  "jax>=0.4.2",
  "triton==2.0.0.dev20221202",
]

[build-system]
requires = [
    "setuptools",
    "wheel",
    "pybind11",
]
build-backend = "setuptools.build_meta"

[tools.setuptools]
packages = ["jax_triton"]
