[project]
name = "jax-triton"
version = "0.1.2"
description = "JAX + OpenAI Triton integration"
readme = "README.md"
requires-python = ">=3.7<3.10"
dependencies = [
  "jax>=0.3.15",
  "triton>=2.0.0.dev20220720",
]

[build-system]
requires = [
    "setuptools",
    "wheel",
    "pybind11",
]
build-backend = "setuptools.build_meta"

[tools.setuptools]
packages = ["jax_triton"]
